config/routes.rb
Rails.application.routes.draw do

  get 'home'   => 'attendances#home'

  get 'aboutus' => 'attendances#about'

  get 'support' => 'attendances#support'

  resources :users

  root 'attendances#home'

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/attendance_controller.rb
class AttendanceController < ApplicationController
  def home
  end

  def about
  end

  def support
  end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  
  layout "attendance"
  def home
  end

  def about
  end

  def support
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :authenticate_user!
  def index
  end

  def new
  end

  def create
  end

  def edit
  end

  def delete
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  layout "user"
  def index
    
  end

  def new
  end

  def create
  end

  def edit
  end

  def delete
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendance_helper.rb
module AttendanceHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/attendances/_header.html.erb
    <header>
      <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%=link_to("Online Attendance Management",home_path,:class=>"navbar-brand")%>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><%=link_to("Home",home_path)%></li>
            <li><%=link_to("About us",aboutus_path)%></li>
            <li ><%=link_to("Help And Support",support_path)%></li>
          </ul>
        </div>
      </div>
    </nav>
    </header>

app/views/attendances/about.html.erb
<h1>Attendances#about</h1>
<p>Find me in app/views/attendances/about.html.erb</p>

app/views/attendances/home.html.erb
    <div class="container">
      <div class="row">
        <div class="col-sm-6" id="right_form_content">
          <h2>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</h2>
        </div>
        <div class="col-sm-5" id="left_form_content1">
          <h3>Sign Up</h3>
        </div>
        <div class="col-sm-5" id="left_form_content2">
          <form role="form">
            <br>
            <div class="form-group">
              <label for="email">Email Address:</label>
              <input type="email" class="form-control" id="email" placeholder="Enter email">
            </div>
            <div class="form-group">
              <label for="pwd">Password:</label>
              <input type="password" class="form-control" id="pwd" placeholder="Enter password">
            </div>
            <div class="checkbox">
              <label><input type="checkbox"> Remember me</label>
            </div>
            <button type="submit" class="btn btn-primary btn-lg btn-block">Submit</button>
            <br><br>
          </form>
        </div>
      </div>
    <div class="col-sm-12">
      <h3>Features Of Online Attendance Management System</h3>
    </div>
    <div class="col-sm-4">
      <h3>Features</h3>
      <%=image_tag("excel.png",:class=>"feature_img")%>
      <p>Excel Report Generate For Admin</p>
    </div>
    <div class="col-sm-4">
      <h3>Features</h3>
      <%=image_tag("excel.png",:class=>"feature_img")%>
      <p>Excel Report Generate F Generate For Generate For Generate Foror Admin</p>  
    </div>
    <div class="col-sm-4">
      <h3>Features</h3>
    </div>
  </div>

app/views/attendances/support.html.erb
<h1>Attendances#support</h1>
<p>Find me in app/views/attendances/support.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Attendance</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/attendance.html.erb
<!DOCTYPE html>
<html>
	<head>
  		<title>Attendance</title>
  		<%= stylesheet_link_tag   'attendance/application.css', media: 'all', 'data-turbolinks-track' => true %>
  		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  		<%= csrf_meta_tags %>	
	</head>
	<body>
		<%=render "attendances/header" %>
		<%= yield %>
		<%=render "footer" %>
	</body>
</html>

app/views/layouts/user.html.erb
<!DOCTYPE html>
<html>
	<head>
  		<title>Attendance</title>
  		<%= stylesheet_link_tag   'dashboard/application.css', media: 'all', 'data-turbolinks-track' => true %>
  		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  		<%= csrf_meta_tags %>	
	</head>
	<body>
	 <div class="container-fluid">
      <div class="row">
		<%=render "users/header" %>
		<%=render "users/sidebar" %>
		<%= yield %>
		</div>
		</div>
	</body>
</html>

app/views/users/_header.html.erb
 <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Online Attendance Management</a>
        </div>
       
      </div>
    </nav>

app/views/users/_sidebar.html.erb
 <div class="col-sm-3 col-md-2 sidebar navbar-collapse collapse" id="navbar">
          <ul class="nav nav-sidebar">
            <li class="active"><a href="#"> Dashboard <span class="sr-only">(current)</span></a></li>
            <li><a href="#">View Profile</a></li>
            <li><a href="#">Edit Profile</a></li>
          </ul>
          <ul class="nav nav-sidebar">
            <li><a href="">View users Today's Status</a></li>
            <li><a href="">View users</a></li>
            <li><a href="">View Reports</a></li>
          </ul>
          <ul class="nav nav-sidebar">
            <li><a href="">Logout</a></li>
          </ul>
        </div>

app/views/users/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/user/create.html.erb</p>

app/views/users/delete.html.erb
<h1>User#delete</h1>
<p>Find me in app/views/user/delete.html.erb</p>

app/views/users/edit.html.erb
<h1>User#edit</h1>
<p>Find me in app/views/user/edit.html.erb</p>

app/views/users/index.html.erb
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          <h1 class="page-header"> Welcome To Dashboard</h1>

                </div>

app/views/users/new.html.erb
<h1>User#new</h1>
<p>Find me in app/views/user/new.html.erb</p>